[tool.poetry]
name = "startpage"
version = "1.2.0-alpha.0"
description = ""
authors = ["Brandon Leon <brandonleon@pm.me>"]

[tool.poetry.dependencies]
python = "^3.9"
python-dotenv = "^0.20.0"
pytest = "^7.0.1"
timeflake = "^0.4.2"
uuid = "^1.30"
fastapi = "^0.75.0"
uvicorn = "^0.17.5"
Jinja2 = "^3.0.3"
aiofiles = "^0.8.0"
timeago = "^1.0.15"
python-multipart = "^0.0.5"
tomlkit = "^0.10.1"

[tool.poetry.dev-dependencies]
pytest-playwright = "^0.3.0"
pytest-sugar = "^0.9.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
