[project]
name = "startpage"
version = "2.8.0a1"
description = ""
authors = [{ name = "Brandon Leon", email = "brandonleon@pm.me" }]
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "aiofiles>=25.1.0",
    "fastapi>=0.129.0",
    "jinja2>=3.1.6",
    "pytest>=9.0.2",
    "pytest-sugar>=1.1.1",
    "python-dotenv>=1.2.1",
    "python-multipart>=0.0.22",
    "timeago>=1.0.15,<2.0.0",
    "timeflake>=0.4.2,<0.5.0",
    "tomlkit>=0.14.0",
    "uvicorn>=0.41.0",
    "uvloop>=0.22.1",
    "requests>=2.31.0,<3.0.0",
    "urllib3>=2.7.0,<3.0.0",
    "httpx>=0.28.1",
]

[dependency-groups]
dev = [
    "mypy>=1.19.1",
]

[tool.setuptools]
packages = ["services"]

[build-system]
requires = ["setuptools>=69.0"]
build-backend = "setuptools.build_meta"
